{
  people {
    __typename
    ... on Author {
      ...name
      agent {
        ...agentName
      }
    }
    ... on Agent {
      ...agentName
      represents {
        ...name
      }
      }
    }
  }

  fragment name on Author {
    firstName
    middleInitial
    lastName
  }

  fragment agentName on Agent {
    firstName
    middleInitial
    lastName
  }
----------------------------------------------------------
  {
  people {
    ... on Author {
      ...name
      agent @include(if: $withAgent) {
        ...name
      }
    }
    ... on Agent {
      ...name
      represents @include(if: $withClient) {
        ...name
      }
      }
    }
  }

  fragment name on Person {
    firstName
    middleInitial
    lastName
  }

  {
  "withAgent": false,
  "withClient": false
}
